// packages/angular/src/stepper/stepper.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-stepper',
  template: `
    <ol class="erb-stepper">
      <li *ngFor="let step of steps; let i = index" class="erb-stepper__step" [attr.aria-current]="currentStep === i ? 'step' : null">
        <span>{{ i + 1 }}</span> <span>{{ step }}</span>
      </li>
    </ol>
  `,
  styleUrls: ['../../../../core/src/components/stepper.css'],
  standalone: true,
  imports: [CommonModule]
})
export class StepperComponent {
  @Input() currentStep = 0;
  @Input() steps: string[] = [];
}

// packages/react/src/stepper/Stepper.tsx
import React from 'react';
import '../../../../core/src/components/stepper.css';

export interface StepperProps { currentStep: number; steps: string[]; }

export const Stepper = ({ currentStep, steps }: StepperProps) => (
  <ol className="erb-stepper">
    {steps.map((step, i) => (
      <li key={i} className="erb-stepper__step" aria-current={currentStep === i ? 'step' : undefined}>
        <span>{i + 1}</span> <span>{step}</span>
      </li>
    ))}
  </ol>
);
