// packages/angular/src/callout/callout.component.ts
import { Component, input } from '@angular/core';

export type CalloutIntent = 'info' | 'success' | 'warning' | 'danger' | 'neutral';

@Component({
  selector: 'erb-callout',
  standalone: true,
  template: `<ng-content></ng-content>`,
  host: {
    class: 'erb-callout',
    '[attr.data-intent]': 'intent()'
  }
})
export class CalloutComponent {
  intent = input<CalloutIntent>('neutral');
}

// packages/react/src/callout/Callout.tsx
import { forwardRef, HTMLAttributes } from 'react';
import { cn } from '../utils';

export interface CalloutProps extends HTMLAttributes<HTMLDivElement> {
  intent?: 'info' | 'success' | 'warning' | 'danger' | 'neutral';
}

export const Callout = forwardRef<HTMLDivElement, CalloutProps>(
  ({ className, intent = 'neutral', children, ...props }, ref) => (
    <div
      ref={ref}
      className={cn('erb-callout', className)}
      data-intent={intent}
      {...props}
    >
      {children}
    </div>
  )
);
Callout.displayName = 'Callout';
