// packages/angular/src/slider/slider.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-slider',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-slider-track"></div>
    <div class="erb-slider-fill" [style.width.%]="percentage" style="left: 0;"></div>
    <div
      class="erb-slider-thumb"
      [style.left.%]="percentage"
      role="slider"
      [attr.tabindex]="disabled ? -1 : 0"
      [attr.aria-valuemin]="min"
      [attr.aria-valuemax]="max"
      [attr.aria-valuenow]="value"
      [attr.aria-disabled]="disabled"
      (keydown)="onKeyDown($event)"
    ></div>
  `,
  host: {
    'class': 'erb-slider-container',
    '[class.erb-slider-container--disabled]': 'disabled',
  }
})
export class SliderComponent {
  @Input() min: number = 0;
  @Input() max: number = 100;
  @Input() step: number = 1;
  @Input() value: number = 0;
  @Input() disabled: boolean = false;

  @Output() valueChange = new EventEmitter<number>();

  isDragging = false;

  constructor(private el: ElementRef) {}

  get percentage(): number {
    return ((this.value - this.min) / (this.max - this.min)) * 100;
  }

  updateValue(newVal: number) {
    const clamped = Math.min(Math.max(newVal, this.min), this.max);
    const stepped = Math.round((clamped - this.min) / this.step) * this.step + this.min;
    const finalVal = Math.min(Math.max(stepped, this.min), this.max);
    
    if (this.value !== finalVal) {
      this.value = finalVal;
      this.valueChange.emit(this.value);
    }
  }

  @HostListener('pointerdown', ['$event'])
  onPointerDown(event: PointerEvent) {
    if (this.disabled) return;
    this.isDragging = true;
    (event.target as HTMLElement).setPointerCapture(event.pointerId);
    this.handlePointerEvent(event);
  }

  @HostListener('pointermove', ['$event'])
  onPointerMove(event: PointerEvent) {
    if (!this.isDragging || this.disabled) return;
    this.handlePointerEvent(event);
  }

  @HostListener('pointerup', ['$event'])
  @HostListener('pointercancel', ['$event'])
  onPointerUp(event: PointerEvent) {
    this.isDragging = false;
    (event.target as HTMLElement).releasePointerCapture(event.pointerId);
  }

  handlePointerEvent(event: PointerEvent) {
    const rect = this.el.nativeElement.getBoundingClientRect();
    const percent = (event.clientX - rect.left) / rect.width;
    this.updateValue(this.min + percent * (this.max - this.min));
  }

  onKeyDown(event: KeyboardEvent) {
    if (this.disabled) return;
    let newVal = this.value;
    switch (event.key) {
      case 'ArrowRight':
      case 'ArrowUp':
        newVal += this.step;
        break;
      case 'ArrowLeft':
      case 'ArrowDown':
        newVal -= this.step;
        break;
      case 'Home':
        newVal = this.min;
        break;
      case 'End':
        newVal = this.max;
        break;
      default:
        return;
    }
    event.preventDefault();
    this.updateValue(newVal);
  }
}

// packages/react/src/slider/Slider.tsx
import React, { useRef, useState, useCallback } from 'react';

export interface SliderProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  min?: number;
  max?: number;
  step?: number;
  value?: number;
  defaultValue?: number;
  onChange?: (value: number) => void;
  disabled?: boolean;
}

export const Slider = React.forwardRef<HTMLDivElement, SliderProps>(
  ({ min = 0, max = 100, step = 1, value, defaultValue, onChange, disabled = false, className = '', ...props }, ref) => {
    const [internalValue, setInternalValue] = useState<number>(defaultValue ?? min);
    const containerRef = useRef<HTMLDivElement | null>(null);
    const isControlled = value !== undefined;
    const currentValue = isControlled ? value : internalValue;

    const clamp = (val: number) => Math.min(Math.max(val, min), max);

    const updateValue = useCallback((newValue: number) => {
      const clampedValue = clamp(newValue);
      const steppedValue = Math.round((clampedValue - min) / step) * step + min;
      const finalValue = clamp(steppedValue);
      
      if (!isControlled) {
        setInternalValue(finalValue);
      }
      if (onChange && currentValue !== finalValue) {
        onChange(finalValue);
      }
    }, [min, max, step, isControlled, currentValue, onChange]);

    const handlePointerDown = (e: React.PointerEvent) => {
      if (disabled || !containerRef.current) return;
      e.currentTarget.setPointerCapture(e.pointerId);
      
      const rect = containerRef.current.getBoundingClientRect();
      const percent = (e.clientX - rect.left) / rect.width;
      updateValue(min + percent * (max - min));
    };

    const handlePointerMove = (e: React.PointerEvent) => {
      if (disabled || !containerRef.current || !e.currentTarget.hasPointerCapture(e.pointerId)) return;
      
      const rect = containerRef.current.getBoundingClientRect();
      const percent = (e.clientX - rect.left) / rect.width;
      updateValue(min + percent * (max - min));
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
      if (disabled) return;
      let newValue = currentValue;
      
      switch (e.key) {
        case 'ArrowRight':
        case 'ArrowUp':
          newValue += step;
          break;
        case 'ArrowLeft':
        case 'ArrowDown':
          newValue -= step;
          break;
        case 'Home':
          newValue = min;
          break;
        case 'End':
          newValue = max;
          break;
        default:
          return;
      }
      
      e.preventDefault();
      updateValue(newValue);
    };

    const percentage = ((currentValue - min) / (max - min)) * 100;

    return (
      <div
        ref={(node) => {
          containerRef.current = node;
          if (typeof ref === 'function') ref(node);
          else if (ref) ref.current = node;
        }}
        className={`erb-slider-container ${disabled ? 'erb-slider-container--disabled' : ''} ${className}`}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={(e) => e.currentTarget.releasePointerCapture(e.pointerId)}
        {...props}
      >
        <div className="erb-slider-track" />
        <div className="erb-slider-fill" style={{ width: `${percentage}%`, left: 0 }} />
        <div
          className="erb-slider-thumb"
          style={{ left: `${percentage}%` }}
          role="slider"
          tabIndex={disabled ? -1 : 0}
          aria-valuemin={min}
          aria-valuemax={max}
          aria-valuenow={currentValue}
          aria-disabled={disabled}
          onKeyDown={handleKeyDown}
        />
      </div>
    );
  }
);
Slider.displayName = 'Slider';
