// packages/react/src/button-group/ButtonGroup.tsx
import { forwardRef, HTMLAttributes } from 'react';
import { cn } from '../utils';

export interface ButtonGroupProps extends HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical';
}

export const ButtonGroup = forwardRef<HTMLDivElement, ButtonGroupProps>(
  ({ className, orientation = 'horizontal', ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn('erb-button-group', className)}
        data-orientation={orientation}
        role="group"
        {...props}
      />
    );
  }
);
ButtonGroup.displayName = 'ButtonGroup';

// packages/angular/src/button-group/button-group.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'erb-button-group',
  standalone: true,
  template: `<ng-content></ng-content>`,
  host: {
    class: 'erb-button-group',
    '[attr.data-orientation]': 'orientation()',
    'role': 'group'
  }
})
export class ButtonGroupComponent {
  orientation = input<'horizontal' | 'vertical'>('horizontal');
}
