// packages/react/src/progress/progress.tsx
import React from 'react';
export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> {
  value: number;
  max?: number;
}
export const Progress = React.forwardRef<HTMLDivElement, ProgressProps>(({ value, max = 100, className = '', ...props }, ref) => {
  const percentage = Math.min(100, Math.max(0, (value / max) * 100));
  return (
    <div ref={ref} className={`erb-progress ${className}`} role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={max} {...props}>
      <div className="erb-progress__bar" style={{ width: `${percentage}%` }} />
    </div>
  );
});
Progress.displayName = 'Progress';

// packages/angular/src/progress/progress.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'erb-progress',
  standalone: true,
  template: `
    <div class="erb-progress" role="progressbar" [attr.aria-valuenow]="value" [attr.aria-valuemin]="0" [attr.aria-valuemax]="max">
      <div class="erb-progress__bar" [style.width.%]="getPercentage()"></div>
    </div>
  `,
})
export class ProgressComponent {
  @Input() value: number = 0;
  @Input() max: number = 100;

  getPercentage(): number {
    return Math.min(100, Math.max(0, (this.value / this.max) * 100));
  }
}
