// packages/react/src/pagination/Pagination.tsx
import React from 'react';
import '../../../../core/src/components/pagination.css';

export interface PaginationProps { currentPage: number; totalPages: number; onPageChange: (page: number) => void; }

export const Pagination = ({ currentPage, totalPages, onPageChange }: PaginationProps) => (
  <nav aria-label="Pagination">
    <ul className="erb-pagination">
      {Array.from({ length: totalPages }).map((_, i) => (
        <li key={i} className="erb-pagination__item">
          <button aria-current={currentPage === i + 1 ? 'page' : undefined} onClick={() => onPageChange(i + 1)}>{i + 1}</button>
        </li>
      ))}
    </ul>
  </nav>
);

// packages/angular/src/pagination/pagination.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-pagination',
  template: `
    <nav aria-label="Pagination">
      <ul class="erb-pagination">
        <li *ngFor="let page of pages" class="erb-pagination__item">
          <button [attr.aria-current]="currentPage === page ? 'page' : null" (click)="onPageChange.emit(page)">{{ page }}</button>
        </li>
      </ul>
    </nav>
  `,
  styleUrls: ['../../../../core/src/components/pagination.css'],
  standalone: true,
  imports: [CommonModule]
})
export class PaginationComponent {
  @Input() currentPage = 1;
  @Input() totalPages = 1;
  @Output() onPageChange = new EventEmitter<number>();
  get pages() { return Array.from({ length: this.totalPages }, (_, i) => i + 1); }
}
