// packages/angular/src/banner/banner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'erb-banner',
  standalone: true,
  template: `<div class="erb-banner erb-banner--{{variant}}" role="alert"><ng-content></ng-content></div>`,
})
export class BannerComponent {
  @Input() variant: 'info' | 'success' | 'warning' | 'error' = 'info';
}

// packages/react/src/banner/banner.tsx
import React from 'react';
export interface BannerProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'info' | 'success' | 'warning' | 'error';
}
export const Banner = React.forwardRef<HTMLDivElement, BannerProps>(({ variant = 'info', className = '', children, ...props }, ref) => {
  return (
    <div ref={ref} className={`erb-banner erb-banner--${variant} ${className}`} role="alert" {...props}>
      {children}
    </div>
  );
});
Banner.displayName = 'Banner';
