// packages/react/src/rating/Rating.tsx
import { useState, KeyboardEvent, forwardRef, Ref } from 'react';

export interface RatingProps {
  max?: number;
  value?: number;
  onChange?: (value: number) => void;
  disabled?: boolean;
}

export const Rating = forwardRef((
  { max = 5, value = 0, onChange, disabled = false }: RatingProps,
  ref: Ref<HTMLDivElement>
) => {
  const [hoverValue, setHoverValue] = useState<number | null>(null);

  const handleKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
    if (disabled) return;
    
    let newValue = value;
    if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
      newValue = Math.min(value + 1, max);
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
      newValue = Math.max(value - 1, 1);
    }

    if (newValue !== value) {
      e.preventDefault();
      onChange?.(newValue);
    }
  };

  return (
    <div
      ref={ref}
      className="erb-rating"
      role="slider"
      aria-valuemin={1}
      aria-valuemax={max}
      aria-valuenow={value}
      aria-disabled={disabled}
      tabIndex={disabled ? -1 : 0}
      onKeyDown={handleKeyDown}
      onMouseLeave={() => setHoverValue(null)}
    >
      {Array.from({ length: max }).map((_, index) => {
        const starValue = index + 1;
        const isActive = starValue <= (hoverValue ?? value);
        
        return (
          <span
            key={starValue}
            className={`erb-rating__item ${isActive ? 'erb-rating__item--active' : ''}`}
            onClick={() => !disabled && onChange?.(starValue)}
            onMouseEnter={() => !disabled && setHoverValue(starValue)}
            aria-hidden="true"
          >
            ★
          </span>
        );
      })}
    </div>
  );
});

Rating.displayName = 'Rating';

// packages/angular/src/rating/rating.component.ts
import { Component, Input, Output, EventEmitter, HostListener, HostBinding } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-rating',
  standalone: true,
  imports: [CommonModule],
  template: `
    <span
      *ngFor="let star of stars; let i = index"
      class="erb-rating__item"
      [class.erb-rating__item--active]="(i + 1) <= (hoverValue || value)"
      (click)="onClick(i + 1)"
      (mouseenter)="onMouseEnter(i + 1)"
      aria-hidden="true"
    >
      ★
    </span>
  `,
})
export class RatingComponent {
  @Input() max = 5;
  @Input() value = 0;
  @Input() disabled = false;
  @Output() valueChange = new EventEmitter<number>();

  hoverValue: number | null = null;

  get stars() {
    return Array(this.max).fill(0);
  }

  @HostBinding('class.erb-rating') hostClass = true;
  @HostBinding('attr.role') role = 'slider';
  @HostBinding('attr.aria-valuemin') ariaValueMin = 1;
  @HostBinding('attr.aria-valuemax') get ariaValueMax() { return this.max; }
  @HostBinding('attr.aria-valuenow') get ariaValueNow() { return this.value; }
  @HostBinding('attr.aria-disabled') get ariaDisabled() { return this.disabled; }
  @HostBinding('attr.tabindex') get tabIndex() { return this.disabled ? -1 : 0; }

  @HostListener('mouseleave')
  onMouseLeave() {
    this.hoverValue = null;
  }

  @HostListener('keydown', ['$event'])
  onKeyDown(event: KeyboardEvent) {
    if (this.disabled) return;
    
    let newValue = this.value;
    if (event.key === 'ArrowRight' || event.key === 'ArrowUp') {
      newValue = Math.min(this.value + 1, this.max);
    } else if (event.key === 'ArrowLeft' || event.key === 'ArrowDown') {
      newValue = Math.max(this.value - 1, 1);
    }

    if (newValue !== this.value) {
      event.preventDefault();
      this.value = newValue;
      this.valueChange.emit(this.value);
    }
  }

  onClick(val: number) {
    if (this.disabled) return;
    this.value = val;
    this.valueChange.emit(this.value);
  }

  onMouseEnter(val: number) {
    if (this.disabled) return;
    this.hoverValue = val;
  }
}
