// packages/angular/src/skip-link/skip-link.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'erb-skip-link',
  template: `<a [href]="href" class="erb-skip-link"><ng-content></ng-content></a>`,
  styleUrls: ['../../../../core/src/components/skip-link.css'],
  standalone: true
})
export class SkipLinkComponent {
  @Input() href!: string;
}

// packages/react/src/skip-link/SkipLink.tsx
import React from 'react';
import '../../../../core/src/components/skip-link.css';

export interface SkipLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> { href: string; children: React.ReactNode; }

export const SkipLink = React.forwardRef<HTMLAnchorElement, SkipLinkProps>(({ href, children, className = '', ...props }, ref) => (
  <a ref={ref} href={href} className={`erb-skip-link ${className}`} {...props}>{children}</a>
));
SkipLink.displayName = 'SkipLink';
