// packages/react/src/switch/Switch.tsx
import { forwardRef, InputHTMLAttributes, useId } from 'react';
import { cn } from '../utils';

export interface SwitchProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'size' | 'type'> {
  size?: 'sm' | 'md' | 'lg';
  label?: string;
}

export const Switch = forwardRef<HTMLInputElement, SwitchProps>(
  ({ className, size = 'md', label, id, disabled, ...props }, ref) => {
    const generatedId = useId();
    const inputId = id ?? generatedId;
    
    return (
      <div className={cn('erb-switch-wrapper', className)}>
        <input
          ref={ref}
          type="checkbox"
          role="switch"
          id={inputId}
          className="erb-switch"
          data-size={size}
          disabled={disabled}
          {...props}
        />
        {label && (
          <label htmlFor={inputId} className="erb-switch-label">
            {label}
          </label>
        )}
      </div>
    );
  }
);
Switch.displayName = 'Switch';

// packages/angular/src/switch/switch.component.ts
import { Component, input, output } from '@angular/core';

export type SwitchSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'erb-switch',
  standalone: true,
  template: `
    <label class="erb-switch-wrapper" [attr.data-disabled]="disabled()">
      <input 
        type="checkbox" 
        role="switch"
        class="erb-switch" 
        [attr.data-size]="size()"
        [disabled]="disabled()"
        [checked]="checked()"
        (change)="onChange($event)"
      />
      <span class="erb-switch-label">
        <ng-content></ng-content>
      </span>
    </label>
  `,
  host: {
    style: 'display: contents;'
  }
})
export class ErbSwitchComponent {
  size = input<SwitchSize>('md');
  disabled = input<boolean>(false);
  checked = input<boolean>(false);
  
  checkedChange = output<boolean>();

  onChange(event: Event) {
    const input = event.target as HTMLInputElement;
    this.checkedChange.emit(input.checked);
  }
}
