// packages/react/src/grid/grid-item.tsx
import { forwardRef, ElementType, ComponentPropsWithRef, CSSProperties } from 'react';
import { cn, ResponsiveValue, resolveResponsiveProps } from '../utils';

export interface GridItemProps extends ComponentPropsWithRef<'div'> {
  as?: ElementType;
  colSpan?: ResponsiveValue<number>;
  rowSpan?: ResponsiveValue<number>;
}

export const GridItem = forwardRef<HTMLElement, GridItemProps>(
  ({ as: Component = 'div', className, colSpan, rowSpan, style, ...props }, ref) => {
    const customStyle = {
      ...style,
      ...resolveResponsiveProps('--erb-grid-item-col-span', colSpan),
      ...resolveResponsiveProps('--erb-grid-item-row-span', rowSpan)
    } as CSSProperties;

    return (
      <Component
        ref={ref}
        className={cn('erb-grid-item', className)}
        style={customStyle}
        {...props}
      />
    );
  }
);

GridItem.displayName = 'GridItem';

// packages/angular/src/grid/grid-item.component.ts
import {  Component, input, computed } from '@angular/core';
import { ResponsiveValue, resolveResponsiveProps } from '../utils';

@Component({
  selector: 'erb-grid-item',
  standalone: true,
  template: `<ng-content></ng-content>`,
  
  host: {
    '[class.erb-grid-item]': 'true',
    '[style]': 'customStyle()'
  }
})
export class GridItemComponent {
  colSpan = input<ResponsiveValue<number>>();
  rowSpan = input<ResponsiveValue<number>>();

  customStyle = computed(() => {
    return {
      ...resolveResponsiveProps('--erb-grid-item-col-span', this.colSpan()),
      ...resolveResponsiveProps('--erb-grid-item-row-span', this.rowSpan())
    };
  });
}
