// packages/react/src/grid/grid.tsx
import { forwardRef, ElementType, ComponentPropsWithRef, CSSProperties } from 'react';
import { cn, ResponsiveValue, resolveResponsiveProps } from '../utils';

export interface GridProps extends ComponentPropsWithRef<'div'> {
  as?: ElementType;
  cols?: ResponsiveValue<number>;
  gap?: ResponsiveValue<number>;
  align?: ResponsiveValue<'start' | 'end' | 'center' | 'stretch'>;
  justify?: ResponsiveValue<'start' | 'end' | 'center' | 'stretch'>;
}

export const Grid = forwardRef<HTMLElement, GridProps>(
  ({ as: Component = 'div', className, cols = 1, gap, align, justify, style, ...props }, ref) => {
    const customStyle = {
      ...style,
      ...resolveResponsiveProps('--erb-grid-cols', cols, (v) => `repeat(${v}, minmax(0, 1fr))`),
      ...resolveResponsiveProps('--erb-grid-gap', gap, (v) => `var(--erb-space-${v})`),
      ...resolveResponsiveProps('--erb-grid-align', align),
      ...resolveResponsiveProps('--erb-grid-justify', justify)
    } as CSSProperties;

    return (
      <Component
        ref={ref}
        className={cn('erb-grid', className)}
        style={customStyle}
        {...props}
      />
    );
  }
);

Grid.displayName = 'Grid';

// packages/angular/src/grid/grid.component.ts
import {  Component, input, computed } from '@angular/core';
import { ResponsiveValue, resolveResponsiveProps } from '../utils';

@Component({
  selector: 'erb-grid',
  standalone: true,
  template: `<ng-content></ng-content>`,
  
  host: {
    '[class.erb-grid]': 'true',
    '[style]': 'customStyle()'
  }
})
export class GridComponent {
  cols = input<ResponsiveValue<number>>(1);
  gap = input<ResponsiveValue<number>>();
  align = input<ResponsiveValue<'start' | 'end' | 'center' | 'stretch'>>();
  justify = input<ResponsiveValue<'start' | 'end' | 'center' | 'stretch'>>();

  customStyle = computed(() => {
    return {
      ...resolveResponsiveProps('--erb-grid-cols', this.cols(), (v) => `repeat(${v}, minmax(0, 1fr))`),
      ...resolveResponsiveProps('--erb-grid-gap', this.gap(), (v) => `var(--erb-space-${v})`),
      ...resolveResponsiveProps('--erb-grid-align', this.align()),
      ...resolveResponsiveProps('--erb-grid-justify', this.justify())
    };
  });
}
