// packages/react/src/accordion/Accordion.tsx
import React, { useState } from 'react';
import '../../../../core/src/components/accordion.css';

export interface AccordionProps { title: React.ReactNode; children: React.ReactNode; defaultExpanded?: boolean; }

export const Accordion = ({ title, children, defaultExpanded = false }: AccordionProps) => {
  const [expanded, setExpanded] = useState(defaultExpanded);
  return (
    <div className="erb-accordion">
      <h3 className="erb-accordion__header">
        <button aria-expanded={expanded} className="erb-accordion__button" onClick={() => setExpanded(!expanded)}>{title}</button>
      </h3>
      <div className="erb-accordion__panel" hidden={!expanded}>{children}</div>
    </div>
  );
};

// packages/angular/src/accordion/accordion.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-accordion',
  template: `
    <div class="erb-accordion">
      <h3 class="erb-accordion__header">
        <button [attr.aria-expanded]="expanded" class="erb-accordion__button" (click)="toggle()">{{ title }}</button>
      </h3>
      <div class="erb-accordion__panel" [hidden]="!expanded">
        <ng-content></ng-content>
      </div>
    </div>
  `,
  styleUrls: ['../../../../core/src/components/accordion.css'],
  standalone: true,
  imports: [CommonModule]
})
export class AccordionComponent {
  @Input() title!: string;
  @Input() expanded = false;
  toggle() { this.expanded = !this.expanded; }
}
