// packages/angular/src/scroll-area/scroll-area.component.ts
import {  Component, input, computed } from '@angular/core';

@Component({
  selector: 'erb-scroll-area',
  standalone: true,
  template: `<ng-content></ng-content>`,
  
  host: {
    '[class.erb-scroll-area]': 'true',
    '[style.--erb-scroll-area-max-height]': 'formattedMaxHeight()'
  }
})
export class ScrollAreaComponent {
  maxHeight = input<number | string>();

  formattedMaxHeight = computed(() => {
    const mh = this.maxHeight();
    if (mh === undefined) return undefined;
    return typeof mh === 'number' ? `${mh}px` : mh;
  });
}

// packages/react/src/scroll-area/scroll-area.tsx
import { forwardRef, ElementType, ComponentPropsWithRef, CSSProperties } from 'react';
import { cn } from '../utils';

export interface ScrollAreaProps extends ComponentPropsWithRef<'div'> {
  as?: ElementType;
  maxHeight?: number | string;
}

export const ScrollArea = forwardRef<HTMLElement, ScrollAreaProps>(
  ({ as: Component = 'div', className, maxHeight, style, ...props }, ref) => {
    return (
      <Component
        ref={ref}
        className={cn('erb-scroll-area', className)}
        style={{ '--erb-scroll-area-max-height': typeof maxHeight === 'number' ? `${maxHeight}px` : maxHeight, ...style } as CSSProperties}
        {...props}
      />
    );
  }
);

ScrollArea.displayName = 'ScrollArea';
