// packages/angular/src/image/image.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-image',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-image-wrapper" [ngClass]="{'erb-image--fallback': error || !src}">
      <img *ngIf="!error && src" [src]="src" [alt]="alt" class="erb-image" [attr.loading]="lazy ? 'lazy' : 'eager'" (error)="onError()" [width]="width" [height]="height" />
      <ng-container *ngIf="error || !src">{{fallbackText}}</ng-container>
    </div>
  `,
})
export class ImageComponent {
  @Input() src: string = '';
  @Input() alt: string = '';
  @Input() lazy: boolean = false;
  @Input() fallbackText: string = 'Image not available';
  @Input() width?: string | number;
  @Input() height?: string | number;

  error = false;

  onError() {
    this.error = true;
  }
}

// packages/react/src/image/image.tsx
import React, { useState } from 'react';
export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  lazy?: boolean;
  fallbackText?: string;
}
export const Image = React.forwardRef<HTMLImageElement, ImageProps>(({ lazy = false, fallbackText = 'Image not available', src, alt, className = '', ...props }, ref) => {
  const [error, setError] = useState(false);
  if (error || !src) {
    return <div className={`erb-image-wrapper erb-image--fallback ${className}`} style={{ width: props.width || '100%', height: props.height || '100px' }}>{fallbackText}</div>;
  }
  return (
    <div className={`erb-image-wrapper ${className}`}>
      <img ref={ref} src={src} alt={alt} className="erb-image" loading={lazy ? 'lazy' : 'eager'} onError={() => setError(true)} {...props} />
    </div>
  );
});
Image.displayName = 'Image';
