// packages/react/src/FileUpload/FileUpload.tsx
import React, { useState, useRef, InputHTMLAttributes } from 'react';

export interface FileUploadProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type' | 'onChange'> {
  onFileSelect?: (files: FileList | null) => void;
  className?: string;
  children?: React.ReactNode;
}

export const FileUpload: React.FC<FileUploadProps> = ({
  onFileSelect,
  className = '',
  children,
  ...props
}) => {
  const [isDragActive, setIsDragActive] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragEnter = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragActive(true);
  };

  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragActive(false);
  };

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragActive(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      onFileSelect?.(e.dataTransfer.files);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    onFileSelect?.(e.target.files);
  };

  const handleClick = () => {
    fileInputRef.current?.click();
  };

  return (
    <div
      className={`erb-file-upload ${className}`.trim()}
      data-drag-active={isDragActive}
      onDragEnter={handleDragEnter}
      onDragLeave={handleDragLeave}
      onDragOver={handleDragOver}
      onDrop={handleDrop}
      onClick={handleClick}
    >
      <input
        type="file"
        ref={fileInputRef}
        className="erb-file-upload-input"
        onChange={handleChange}
        {...props}
      />
      {children || <span>Drag & Drop files here or click to browse</span>}
    </div>
  );
};

// packages/angular/src/FileUpload/FileUpload.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-file-upload',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="erb-file-upload"
      [ngClass]="className"
      [attr.data-drag-active]="isDragActive"
      (dragenter)="onDragEnter($event)"
      (dragleave)="onDragLeave($event)"
      (dragover)="onDragOver($event)"
      (drop)="onDrop($event)"
      (click)="onClick()"
    >
      <input
        type="file"
        #fileInput
        class="erb-file-upload-input"
        (change)="onFileChange($event)"
        [multiple]="multiple"
        [accept]="accept"
      />
      <ng-content></ng-content>
      <span *ngIf="!hasContent">Drag & Drop files here or click to browse</span>
    </div>
  `,
})
export class FileUploadComponent {
  @Input() className: string = '';
  @Input() multiple: boolean = false;
  @Input() accept: string = '';
  @Output() fileSelect = new EventEmitter<FileList | null>();

  @ViewChild('fileInput') fileInput!: ElementRef<HTMLInputElement>;
  @ViewChild('content', { static: true }) content?: ElementRef;

  isDragActive: boolean = false;
  
  get hasContent(): boolean {
    return false; // For simplcity, assume no content for basic angular transclusion check unless more complex DOM checking
  }

  onDragEnter(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.isDragActive = true;
  }

  onDragLeave(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.isDragActive = false;
  }

  onDragOver(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
  }

  onDrop(event: DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.isDragActive = false;

    if (event.dataTransfer?.files && event.dataTransfer.files.length > 0) {
      this.fileSelect.emit(event.dataTransfer.files);
    }
  }

  onFileChange(event: Event) {
    const input = event.target as HTMLInputElement;
    this.fileSelect.emit(input.files);
  }

  onClick() {
    this.fileInput.nativeElement.click();
  }
}
