// packages/react/src/flex/flex.tsx
import { forwardRef, ElementType, ComponentPropsWithRef, CSSProperties } from 'react';
import { cn, ResponsiveValue, resolveResponsiveProps } from '../utils';

export interface FlexProps extends ComponentPropsWithRef<'div'> {
  as?: ElementType;
  direction?: ResponsiveValue<'row' | 'row-reverse' | 'column' | 'column-reverse'>;
  gap?: ResponsiveValue<number>;
  align?: ResponsiveValue<'start' | 'end' | 'center' | 'stretch' | 'baseline'>;
  justify?: ResponsiveValue<'start' | 'end' | 'center' | 'space-between' | 'space-around' | 'space-evenly'>;
  wrap?: ResponsiveValue<'nowrap' | 'wrap' | 'wrap-reverse'>;
}

const justifyMap: Record<string, string> = {
  start: 'flex-start',
  end: 'flex-end',
  center: 'center',
  'space-between': 'space-between',
  'space-around': 'space-around',
  'space-evenly': 'space-evenly'
};

const alignMap: Record<string, string> = {
  start: 'flex-start',
  end: 'flex-end',
  center: 'center',
  stretch: 'stretch',
  baseline: 'baseline'
};

export const Flex = forwardRef<HTMLElement, FlexProps>(
  ({ as: Component = 'div', className, direction, gap, align, justify, wrap, style, ...props }, ref) => {
    const customStyle = {
      ...style,
      ...resolveResponsiveProps('--erb-flex-direction', direction),
      ...resolveResponsiveProps('--erb-flex-gap', gap, (v) => `var(--erb-space-${v})`),
      ...resolveResponsiveProps('--erb-flex-align', align, (v) => alignMap[v] || v),
      ...resolveResponsiveProps('--erb-flex-justify', justify, (v) => justifyMap[v] || v),
      ...resolveResponsiveProps('--erb-flex-wrap', wrap)
    } as CSSProperties;

    return (
      <Component
        ref={ref}
        className={cn('erb-flex', className)}
        style={customStyle}
        {...props}
      />
    );
  }
);

Flex.displayName = 'Flex';

// packages/angular/src/flex/flex.component.ts
import {  Component, input, computed } from '@angular/core';
import { ResponsiveValue, resolveResponsiveProps } from '../utils';

const justifyMap: Record<string, string> = {
  start: 'flex-start',
  end: 'flex-end',
  center: 'center',
  'space-between': 'space-between',
  'space-around': 'space-around',
  'space-evenly': 'space-evenly'
};

const alignMap: Record<string, string> = {
  start: 'flex-start',
  end: 'flex-end',
  center: 'center',
  stretch: 'stretch',
  baseline: 'baseline'
};

@Component({
  selector: 'erb-flex',
  standalone: true,
  template: `<ng-content></ng-content>`,
  
  host: {
    '[class.erb-flex]': 'true',
    '[style]': 'customStyle()'
  }
})
export class FlexComponent {
  direction = input<ResponsiveValue<'row' | 'row-reverse' | 'column' | 'column-reverse'>>();
  gap = input<ResponsiveValue<number>>();
  align = input<ResponsiveValue<'start' | 'end' | 'center' | 'stretch' | 'baseline'>>();
  justify = input<ResponsiveValue<'start' | 'end' | 'center' | 'space-between' | 'space-around' | 'space-evenly'>>();
  wrap = input<ResponsiveValue<'nowrap' | 'wrap' | 'wrap-reverse'>>();

  customStyle = computed(() => {
    return {
      ...resolveResponsiveProps('--erb-flex-direction', this.direction()),
      ...resolveResponsiveProps('--erb-flex-gap', this.gap(), (v) => `var(--erb-space-${v})`),
      ...resolveResponsiveProps('--erb-flex-align', this.align(), (v) => alignMap[v as string] || v),
      ...resolveResponsiveProps('--erb-flex-justify', this.justify(), (v) => justifyMap[v as string] || v),
      ...resolveResponsiveProps('--erb-flex-wrap', this.wrap())
    };
  });
}
