// packages/angular/src/divider/divider.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'erb-divider',
  standalone: true,
  template: `<hr class="erb-divider" [attr.data-orientation]="orientation()" role="separator" [attr.aria-orientation]="orientation()" />`,
  host: {
    display: 'contents'
  }
})
export class DividerComponent {
  orientation = input<'horizontal' | 'vertical'>('horizontal');
}

// packages/react/src/divider/Divider.tsx
import { forwardRef, HTMLAttributes } from 'react';
import { cn } from '../utils';

export interface DividerProps extends HTMLAttributes<HTMLHRElement> {
  orientation?: 'horizontal' | 'vertical';
}

export const Divider = forwardRef<HTMLHRElement, DividerProps>(
  ({ className, orientation = 'horizontal', ...props }, ref) => {
    return (
      <hr
        ref={ref}
        className={cn('erb-divider', className)}
        data-orientation={orientation}
        role="separator"
        aria-orientation={orientation}
        {...props}
      />
    );
  }
);
Divider.displayName = 'Divider';
