// packages/angular/src/CTA/cta.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ErbButtonDirective } from '../button/button.directive';

export interface CTAActionProps {
  label: string;
}

@Component({
  selector: 'erb-cta',
  standalone: true,
  imports: [CommonModule, ErbButtonDirective],
  template: `
    <div class="erb-cta" [ngClass]="className()">
      <h2 class="erb-cta-title">{{ title() }}</h2>
      <p *ngIf="description()" class="erb-cta-description">{{ description() }}</p>
      <div *ngIf="primaryAction() || secondaryAction()" class="erb-cta-actions">
        <button *ngIf="primaryAction()" erbButton variant="solid" color="primary" (click)="primaryClick.emit()">
          {{ primaryAction()?.label }}
        </button>
        <button *ngIf="secondaryAction()" erbButton variant="outline" (click)="secondaryClick.emit()">
          {{ secondaryAction()?.label }}
        </button>
      </div>
    </div>
  `,
})
export class CTAComponent {
  className = input<string>('');
  title = input.required<string>();
  description = input<string>();
  primaryAction = input<CTAActionProps>();
  secondaryAction = input<CTAActionProps>();
  primaryClick = output<void>();
  secondaryClick = output<void>();
}

// packages/react/src/CTA/CTA.tsx
import React from 'react';
import { Button } from '../button';

interface ActionProps {
  label: string;
  onClick: () => void;
}

export interface CTAProps {
  className?: string;
  title: string;
  description?: string;
  primaryAction?: ActionProps;
  secondaryAction?: ActionProps;
}

export const CTA: React.FC<CTAProps> = ({
  className = '',
  title,
  description,
  primaryAction,
  secondaryAction,
  ...props
}) => {
  return (
    <div className={`erb-cta ${className}`} {...props}>
      <h2 className="erb-cta-title">{title}</h2>
      {description && <p className="erb-cta-description">{description}</p>}
      {(primaryAction || secondaryAction) && (
        <div className="erb-cta-actions">
          {primaryAction && (
            <Button variant="solid" color="primary" onClick={primaryAction.onClick}>
              {primaryAction.label}
            </Button>
          )}
          {secondaryAction && (
            <Button variant="outline" onClick={secondaryAction.onClick}>
              {secondaryAction.label}
            </Button>
          )}
        </div>
      )}
    </div>
  );
};
