// packages/angular/src/loading-overlay/loading-overlay.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-loading-overlay',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-loading-overlay" *ngIf="active">
      <div class="erb-loading-overlay__spinner" aria-label="Loading"></div>
    </div>
  `,
})
export class LoadingOverlayComponent {
  @Input() active: boolean = true;
}

// packages/react/src/loading-overlay/loading-overlay.tsx
import React from 'react';
export interface LoadingOverlayProps extends React.HTMLAttributes<HTMLDivElement> {
  active?: boolean;
}
export const LoadingOverlay = React.forwardRef<HTMLDivElement, LoadingOverlayProps>(({ active = true, className = '', ...props }, ref) => {
  if (!active) return null;
  return (
    <div ref={ref} className={`erb-loading-overlay ${className}`} {...props}>
      <div className="erb-loading-overlay__spinner" aria-label="Loading" />
    </div>
  );
});
LoadingOverlay.displayName = 'LoadingOverlay';
