// apps/demo-react/src/examples/ButtonExample.tsx
import { Button, Badge, Tag, Heading } from '@glowing-sea-studio/erebus-react';

export default function ButtonExample() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <section>
        <Heading level={3}>Buttons</Heading>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center', marginTop: '1rem' }}>
          <Button variant="solid" color="primary">Primary Solid</Button>
          <Button variant="outline" color="neutral">Neutral Outline</Button>
          <Button variant="ghost" color="danger">Danger Ghost</Button>
        </div>
      </section>

      <section>
        <Heading level={3}>Badges & Tags</Heading>
        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center', marginTop: '1rem' }}>
          <Badge color="success">Success Badge</Badge>
          <Badge color="warning">Warning Badge</Badge>
          <Tag>Default Tag</Tag>
        </div>
      </section>
    </div>
  );
}

// apps/demo-angular/src/app/examples/button-example.component.ts
import { Component } from '@angular/core';
import { ErbButtonDirective, BadgeComponent, TagComponent } from '@glowing-sea-studio/erebus-angular';

@Component({
  selector: 'app-button-example',
  standalone: true,
  imports: [ErbButtonDirective, BadgeComponent, TagComponent],
  template: `
    <div style="display: flex; flex-direction: column; gap: 2rem;">
      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Buttons</h3>
        <div style="display: flex; gap: 1rem; flex-wrap: wrap; align-items: center; margin-top: 1rem;">
          <button erbButton variant="solid" color="primary">Primary Solid</button>
          <button erbButton variant="outline" color="neutral">Neutral Outline</button>
          <button erbButton variant="ghost" color="danger">Danger Ghost</button>
        </div>
      </section>

      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Badges & Tags</h3>
        <div style="display: flex; gap: 1rem; flex-wrap: wrap; align-items: center; margin-top: 1rem;">
          <erb-badge color="success">Success Badge</erb-badge>
          <erb-badge color="warning">Warning Badge</erb-badge>
          <erb-tag>Default Tag</erb-tag>
        </div>
      </section>
    </div>
  `
})
export class ButtonExampleComponent {}
