// packages/angular/src/badge/badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'erb-badge',
  standalone: true,
  template: `
    <span
      class="erb-badge"
      [class.erb-badge--variant-solid]="variant === 'solid'"
      [class.erb-badge--variant-outline]="variant === 'outline'"
      [class.erb-badge--variant-soft]="variant === 'soft'"
      [class]="'erb-badge--color-' + color"
      [class]="'erb-badge--size-' + size"
      [class]="'erb-badge--shape-' + shape"
    >
      <ng-content></ng-content>
    </span>
  `,
  styleUrls: []
})
export class BadgeComponent {
  @Input() variant: 'solid' | 'outline' | 'soft' = 'solid';
  @Input() color: 'primary' | 'success' | 'warning' | 'danger' | 'neutral' = 'primary';
  @Input() size: 'sm' | 'md' | 'lg' = 'md';
  @Input() shape: 'rounded' | 'pill' = 'rounded';
}

// packages/react/src/badge/Badge.tsx
import React from 'react';
export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'solid' | 'outline' | 'soft';
  color?: 'primary' | 'success' | 'warning' | 'danger' | 'neutral';
  size?: 'sm' | 'md' | 'lg';
  shape?: 'rounded' | 'pill';
}

export const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(
  ({ className = '', variant = 'solid', color = 'primary', size = 'md', shape = 'rounded', children, ...props }, ref) => {
    const classNames = [
      'erb-badge',
      `erb-badge--variant-${variant}`,
      `erb-badge--color-${color}`,
      `erb-badge--size-${size}`,
      `erb-badge--shape-${shape}`,
      className,
    ].filter(Boolean).join(' ');

    return (
      <span ref={ref} className={classNames} {...props}>
        {children}
      </span>
    );
  }
);
Badge.displayName = 'Badge';
