// packages/react/src/lightbox/Lightbox.tsx
import React, { useEffect } from 'react';

export interface LightboxProps {
  isOpen: boolean;
  onClose: () => void;
  imageSrc?: string;
  imageAlt?: string;
}

export const Lightbox: React.FC<LightboxProps> = ({ isOpen, onClose, imageSrc, imageAlt }) => {
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    if (isOpen) {
      window.addEventListener('keydown', handleKeyDown);
    }
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen || !imageSrc) return null;

  return (
    <div className="erb-lightbox" onClick={onClose} role="dialog" aria-modal="true">
      <div className="erb-lightbox-content" onClick={(e) => e.stopPropagation()}>
        <button className="erb-lightbox-close" onClick={onClose} aria-label="Close">
          &times;
        </button>
        <img src={imageSrc} alt={imageAlt} className="erb-lightbox-img" />
      </div>
    </div>
  );
};

// packages/angular/src/lightbox/lightbox.component.ts
import { Component, Input, Output, EventEmitter, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-lightbox',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-lightbox" *ngIf="isOpen" (click)="close.emit()" role="dialog" aria-modal="true">
      <div class="erb-lightbox-content" (click)="$event.stopPropagation()">
        <button class="erb-lightbox-close" (click)="close.emit()" aria-label="Close">
          &times;
        </button>
        <img *ngIf="imageSrc" [src]="imageSrc" [alt]="imageAlt" class="erb-lightbox-img" />
      </div>
    </div>
  `
})
export class LightboxComponent {
  @Input() isOpen = false;
  @Input() imageSrc?: string;
  @Input() imageAlt?: string;
  @Output() close = new EventEmitter<void>();

  @HostListener('window:keydown.escape', ['$event'])
  onEscape() {
    if (this.isOpen) {
      this.close.emit();
    }
  }
}
