// packages/react/src/Stat/Stat.tsx
import React from 'react';

export interface StatProps {
  className?: string;
  label: string;
  value: string | number;
  helpText?: string;
}

export const Stat: React.FC<StatProps> = ({
  className = '',
  label,
  value,
  helpText,
  ...props
}) => {
  return (
    <div className={`erb-stat ${className}`} {...props}>
      <p className="erb-stat-label">{label}</p>
      <p className="erb-stat-value">{value}</p>
      {helpText && <p className="erb-stat-help-text">{helpText}</p>}
    </div>
  );
};

// packages/angular/src/stat/stat.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({


  selector: 'erb-stat',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-stat" [ngClass]="className()">
      <p class="erb-stat-label">{{ label() }}</p>
      <p class="erb-stat-value">{{ value() }}</p>
      <p *ngIf="helpText()" class="erb-stat-help-text">{{ helpText() }}</p>
    </div>
  `,
})
export class StatComponent {
  className = input<string>('');
  label = input.required<string>();
  value = input.required<string | number>();
  helpText = input<string>();
}
