// packages/react/src/field/Field.tsx
import React, { forwardRef } from 'react';
import { clsx } from 'clsx';
import { Label } from '../label';

export interface FieldProps extends React.HTMLAttributes<HTMLDivElement> {
  label?: string;
  hint?: string;
  error?: string;
  horizontal?: boolean;
  required?: boolean;
  disabled?: boolean;
}

export const Field = forwardRef<HTMLDivElement, FieldProps>(
  ({ children, className, label, hint, error, horizontal, required, disabled, ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={clsx(
          'erb-field',
          {
            'erb-field--horizontal': horizontal,
          },
          className
        )}
        {...props}
      >
        {label && (
          <Label required={required} disabled={disabled}>
            {label}
          </Label>
        )}
        <div className="erb-field__content">
          {children}
          {error ? (
            <div className="erb-field__error">{error}</div>
          ) : hint ? (
            <div className="erb-field__hint">{hint}</div>
          ) : null}
        </div>
      </div>
    );
  }
);

Field.displayName = 'Field';

// packages/angular/src/field/field.component.ts
import { Component, input } from '@angular/core';
import { ErbLabelComponent } from '../label/label.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'erb-field',
  standalone: true,
  imports: [CommonModule, ErbLabelComponent],
  template: `
    <div
      class="erb-field"
      [class.erb-field--horizontal]="horizontal()"
    >
      <erb-label *ngIf="label()" [required]="required()" [disabled]="disabled()">
        {{ label() }}
      </erb-label>
      <div class="erb-field__content">
        <ng-content></ng-content>
        <div *ngIf="error()" class="erb-field__error">{{ error() }}</div>
        <div *ngIf="!error() && hint()" class="erb-field__hint">{{ hint() }}</div>
      </div>
    </div>
  `,
  host: {
    style: 'display: contents;'
  }
})
export class ErbFieldComponent {
  label = input<string>();
  hint = input<string>();
  error = input<string>();
  horizontal = input<boolean>(false);
  required = input<boolean>(false);
  disabled = input<boolean>(false);
}
