// packages/react/src/Hero/Hero.tsx
import React from 'react';
import { Button } from '../button';

interface ActionProps {
  label: string;
  onClick: () => void;
}

export interface HeroProps {
  className?: string;
  title: string;
  subtitle?: string;
  primaryAction?: ActionProps;
  secondaryAction?: ActionProps;
}

export const Hero: React.FC<HeroProps> = ({
  className = '',
  title,
  subtitle,
  primaryAction,
  secondaryAction,
  ...props
}) => {
  return (
    <div className={`erb-hero ${className}`} {...props}>
      <h1 className="erb-hero-title">{title}</h1>
      {subtitle && <p className="erb-hero-subtitle">{subtitle}</p>}
      {(primaryAction || secondaryAction) && (
        <div className="erb-hero-actions">
          {primaryAction && (
            <Button variant="solid" color="primary" onClick={primaryAction.onClick}>
              {primaryAction.label}
            </Button>
          )}
          {secondaryAction && (
            <Button variant="outline" onClick={secondaryAction.onClick}>
              {secondaryAction.label}
            </Button>
          )}
        </div>
      )}
    </div>
  );
};

// packages/angular/src/Hero/hero.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ErbButtonDirective } from '../button/button.directive';

export interface HeroActionProps {
  label: string;
}

@Component({
  selector: 'erb-hero',
  standalone: true,
  imports: [CommonModule, ErbButtonDirective],
  template: `
    <div class="erb-hero" [ngClass]="className()">
      <h1 class="erb-hero-title">{{ title() }}</h1>
      <p *ngIf="subtitle()" class="erb-hero-subtitle">{{ subtitle() }}</p>
      <div *ngIf="primaryAction() || secondaryAction()" class="erb-hero-actions">
        <button *ngIf="primaryAction()" erbButton variant="solid" color="primary" (click)="primaryClick.emit()">
          {{ primaryAction()?.label }}
        </button>
        <button *ngIf="secondaryAction()" erbButton variant="outline" (click)="secondaryClick.emit()">
          {{ secondaryAction()?.label }}
        </button>
      </div>
    </div>
  `,
})
export class HeroComponent {
  className = input<string>('');
  title = input.required<string>();
  subtitle = input<string>();
  primaryAction = input<HeroActionProps>();
  secondaryAction = input<HeroActionProps>();
  primaryClick = output<void>();
  secondaryClick = output<void>();
}
