// packages/react/src/FeatureGrid/FeatureGrid.tsx
import React from 'react';

export interface FeatureProps {
  title: string;
  description: string;
}

export interface FeatureGridProps {
  className?: string;
  features: FeatureProps[];
}

export const FeatureGrid: React.FC<FeatureGridProps> = ({
  className = '',
  features,
  ...props
}) => {
  return (
    <div className={`erb-featuregrid ${className}`} {...props}>
      {features.map((feature, idx) => (
        <div key={idx} className="erb-featuregrid-item">
          <h3 className="erb-featuregrid-title">{feature.title}</h3>
          <p className="erb-featuregrid-description">{feature.description}</p>
        </div>
      ))}
    </div>
  );
};

// packages/angular/src/FeatureGrid/featuregrid.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface FeatureProps {
  title: string;
  description: string;
}

@Component({
  selector: 'erb-featuregrid',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-featuregrid" [ngClass]="className()">
      <div *ngFor="let feature of features()" class="erb-featuregrid-item">
        <h3 class="erb-featuregrid-title">{{ feature.title }}</h3>
        <p class="erb-featuregrid-description">{{ feature.description }}</p>
      </div>
    </div>
  `,
})
export class FeatureGridComponent {
  className = input<string>('');
  features = input.required<FeatureProps[]>();
}
