// packages/react/src/breadcrumb/Breadcrumb.tsx
import React from 'react';
import '../../../../core/src/components/breadcrumb.css';

export interface BreadcrumbProps { children: React.ReactNode; ariaLabel?: string; }

export const Breadcrumb = ({ children, ariaLabel = 'Breadcrumb' }: BreadcrumbProps) => (
  <nav aria-label={ariaLabel} className="erb-breadcrumb">
    <ol className="erb-breadcrumb__list">
      {React.Children.map(children, (child, i) => (
        <li className="erb-breadcrumb__item">
          {child}
          {i < React.Children.count(children) - 1 && <span className="erb-breadcrumb__separator" aria-hidden="true">/</span>}
        </li>
      ))}
    </ol>
  </nav>
);

// packages/angular/src/breadcrumb/breadcrumb.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'erb-breadcrumb',
  template: `
    <nav [attr.aria-label]="ariaLabel" class="erb-breadcrumb">
      <ol class="erb-breadcrumb__list">
        <ng-content></ng-content>
      </ol>
    </nav>
  `,
  styleUrls: ['../../../../core/src/components/breadcrumb.css'],
  standalone: true
})
export class BreadcrumbComponent {
  @Input() ariaLabel = 'Breadcrumb';
}
