// apps/demo-react/src/pages/LayoutNavigationPage.tsx
import { ComponentPreview } from '../docs/ComponentPreview';
import LayoutNavigationExample from '../examples/LayoutNavigationExample';
import layoutNavigationExampleCode from '../examples/LayoutNavigationExample.tsx?raw';

export function LayoutNavigationPage() {
  return (
    <div>
      <h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', marginBottom: '1rem', color: 'var(--erb-color-neutral-fg)' }}>Layout & Navigation</h1>
      <p style={{ color: 'var(--erb-color-fg-muted)', marginBottom: '2rem', fontSize: '1.125rem' }}>
        Components used for page layout and navigation.
      </p>

      <ComponentPreview
        title="Layout & Navigation Components"
        description="A showcase of breadcrumbs and cards."
        code={layoutNavigationExampleCode}
      >
        <LayoutNavigationExample />
      </ComponentPreview>
    </div>
  );
}

// apps/demo-angular/src/app/pages/layout-navigation-page.component.ts
import { Component } from '@angular/core';
import { ComponentPreviewComponent } from '../docs/component-preview.component';
import { LayoutNavigationExampleComponent } from '../examples/layout-navigation-example.component';
import { layoutNavigationExampleCode } from '../examples/layout-navigation-example.code';

@Component({
  selector: 'app-layout-navigation-page',
  standalone: true,
  imports: [ComponentPreviewComponent, LayoutNavigationExampleComponent],
  template: `
    <div>
      <h1 style="font-size: 2.5rem; font-weight: bold; margin-bottom: 1rem; color: var(--erb-color-neutral-fg);">Layout & Navigation</h1>
      <p style="color: var(--erb-color-fg-muted); margin-bottom: 2rem; font-size: 1.125rem;">
        Components used for page layout and navigation.
      </p>

      <app-component-preview
        title="Layout & Navigation Components"
        description="A showcase of breadcrumbs and cards."
        [codeTs]="layoutNavigationExampleCode"
        [codeHtml]="'<app-layout-navigation-example></app-layout-navigation-example>'">
        <app-layout-navigation-example></app-layout-navigation-example>
      </app-component-preview>
    </div>
  `
})
export class LayoutNavigationPageComponent {
  layoutNavigationExampleCode = layoutNavigationExampleCode;
}
