// apps/demo-angular/src/app/examples/advanced-components-example.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ErbTabsComponent, ErbTabsListComponent, ErbTabDirective, ErbTabsPanelComponent,
  AccordionComponent,
  ErbModalOverlayComponent, ErbModalContentComponent, ErbModalHeaderComponent, ErbModalTitleComponent, ErbModalBodyComponent, ErbModalFooterComponent, ErbButtonDirective,
  CarouselComponent,
  HeroComponent, LogoCloudComponent, FeatureGridComponent, TestimonialComponent, FAQComponent, CTAComponent,
  ErbStatComponent, TimelineComponent, TimelineItemComponent, EmptyStateComponent
} from '@glowing-sea-studio/erebus-angular';

@Component({
  selector: 'app-advanced-components-example',
  standalone: true,
  imports: [
    CommonModule,
    ErbTabsComponent, ErbTabsListComponent, ErbTabDirective, ErbTabsPanelComponent,
    AccordionComponent,
    ErbModalOverlayComponent, ErbModalContentComponent, ErbModalHeaderComponent, ErbModalTitleComponent, ErbModalBodyComponent, ErbModalFooterComponent, ErbButtonDirective,
    CarouselComponent,
    HeroComponent, LogoCloudComponent, FeatureGridComponent, TestimonialComponent, FAQComponent, CTAComponent,
    ErbStatComponent, TimelineComponent, TimelineItemComponent, EmptyStateComponent
  ],
  template: `
    <div style="display: flex; flex-direction: column; gap: 2rem;">
      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Tabs</h3>
        <div style="margin-top: 1rem;">
          <erb-tabs>
            <erb-tabs-list>
              <button erbTab>Tab 1</button>
              <button erbTab>Tab 2</button>
              <button erbTab>Tab 3</button>
            </erb-tabs-list>
            <div style="margin-top: 1rem;">
              <erb-tabs-panel>Content for Tab 1</erb-tabs-panel>
              <erb-tabs-panel>Content for Tab 2</erb-tabs-panel>
              <erb-tabs-panel>Content for Tab 3</erb-tabs-panel>
            </div>
          </erb-tabs>
        </div>
      </section>

      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Accordion</h3>
        <div style="display: flex; flex-direction: column; gap: 0.5rem; margin-top: 1rem;">
          <erb-accordion title="Is it accessible?">
            Yes. It adheres to the WAI-ARIA design pattern.
          </erb-accordion>
          <erb-accordion title="Is it styled?">
            Yes. It comes with default styles that matches the other components' aesthetic.
          </erb-accordion>
        </div>
      </section>

      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Modal</h3>
        <div style="margin-top: 1rem;">
          <button erbButton (click)="isModalOpen.set(true)">Open Modal</button>
          <div *ngIf="isModalOpen()">
            <erb-modal-overlay (click)="isModalOpen.set(false)"></erb-modal-overlay>
            <erb-modal-content>
              <erb-modal-header>
                <erb-modal-title>Modal Title</erb-modal-title>
              </erb-modal-header>
              <erb-modal-body>
                <p style="color: var(--erb-color-neutral-fg); font-family: var(--erb-font-sans);">This is the modal body content. You can put any component here.</p>
              </erb-modal-body>
              <erb-modal-footer>
                <button erbButton variant="outline" (click)="isModalOpen.set(false)">Cancel</button>
                <button erbButton variant="solid" color="primary" (click)="isModalOpen.set(false)">Confirm</button>
              </erb-modal-footer>
            </erb-modal-content>
          </div>
        </div>
      </section>

      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Carousel</h3>
        <div style="max-width: 400px; margin-top: 1rem;">
          <erb-carousel [images]="[
            { src: 'https://picsum.photos/400/200?random=1', alt: 'Slide 1' },
            { src: 'https://picsum.photos/400/200?random=2', alt: 'Slide 2' },
            { src: 'https://picsum.photos/400/200?random=3', alt: 'Slide 3' }
          ]"></erb-carousel>
        </div>
      </section>

      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Marketing / Display</h3>
        <div style="display: flex; flex-direction: column; gap: 3rem; margin-top: 1rem;">
          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">Hero</h4>
            <erb-hero
              title="Build faster with Erebus"
              subtitle="The ultimate design system for your next big project."
              [primaryAction]="{ label: 'Get Started' }"
              [secondaryAction]="{ label: 'Documentation' }">
            </erb-hero>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">LogoCloud</h4>
            <erb-logocloud
              title="Trusted by innovative teams worldwide"
              [logos]="[
                { src: 'https://via.placeholder.com/150x50?text=Logo+1', alt: 'Logo 1' },
                { src: 'https://via.placeholder.com/150x50?text=Logo+2', alt: 'Logo 2' },
                { src: 'https://via.placeholder.com/150x50?text=Logo+3', alt: 'Logo 3' },
                { src: 'https://via.placeholder.com/150x50?text=Logo+4', alt: 'Logo 4' }
              ]">
            </erb-logocloud>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">FeatureGrid</h4>
            <erb-featuregrid
              [features]="[
                { title: 'Lightning Fast', description: 'Built on modern web standards for maximum performance.' },
                { title: 'Accessible', description: 'Fully compliant with WCAG 2.1 AA accessibility guidelines.' },
                { title: 'Customizable', description: 'Easily adapt the design system to match your brand identity.' }
              ]">
            </erb-featuregrid>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">Testimonial</h4>
            <erb-testimonial
              quote="This design system is amazing! It makes building applications so much faster."
              author="John Doe"
              role="Frontend Developer"
              avatarUrl="https://i.pravatar.cc/150?u=4"
            ></erb-testimonial>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">FAQ</h4>
            <erb-faq
              [items]="[
                { question: 'What is Erebus?', answer: 'Erebus is a comprehensive design system for modern web applications.' },
                { question: 'Is it free to use?', answer: 'Yes, Erebus is completely open-source and free to use in your projects.' },
                { question: 'Does it support Angular and React?', answer: 'Absolutely! We provide first-class support for both frameworks.' }
              ]">
            </erb-faq>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">CTA</h4>
            <erb-cta
              title="Ready to dive in?"
              description="Start building your next masterpiece today with Erebus UI."
              [primaryAction]="{ label: 'Get Started' }"
              [secondaryAction]="{ label: 'Learn More' }">
            </erb-cta>
          </div>
        </div>
      </section>

      <section>
        <h3 style="font-size: 1.25rem; font-weight: bold; color: var(--erb-color-neutral-fg);">Data Display & States</h3>
        <div style="display: flex; flex-direction: column; gap: 3rem; margin-top: 1rem;">
          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">Stat</h4>
            <div style="display: flex; gap: 2rem;">
              <erb-stat label="Total Users" value="10,234" helpText="+12% from last month"></erb-stat>
              <erb-stat label="Revenue" value="$43,000" helpText="+5% from last month"></erb-stat>
            </div>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">Timeline</h4>
            <erb-timeline>
              <erb-timeline-item title="Project Started" description="Initial commit and setup."></erb-timeline-item>
              <erb-timeline-item title="Alpha Release" description="First version released for internal testing."></erb-timeline-item>
              <erb-timeline-item title="Public Beta" description="Opened to the public." [isLast]="true"></erb-timeline-item>
            </erb-timeline>
          </div>

          <div>
            <h4 style="font-size: 1.125rem; font-weight: bold; color: var(--erb-color-neutral-fg); margin-bottom: 0.5rem;">EmptyState</h4>
            <erb-empty-state
              title="No projects found"
              description="Get started by creating a new project."
            >
              <button erbButton variant="solid" color="primary">Create Project</button>
            </erb-empty-state>
          </div>
        </div>
      </section>
    </div>
  `
})
export class AdvancedComponentsExampleComponent {
  isModalOpen = signal(false);
}

// apps/demo-react/src/examples/AdvancedComponentsExample.tsx
import {
  Tabs, TabsList, Tab, TabsPanel,
  Accordion,
  Modal, ModalContent, ModalHeader, ModalTitle, ModalBody, ModalFooter, ModalOverlay, Button,
  Carousel,
  Hero, LogoCloud, FeatureGrid, Testimonial, FAQ, CTA,
  Stat, Timeline, EmptyState, Heading, Text
} from '@glowing-sea-studio/erebus-react';
import { useState } from 'react';

export default function AdvancedComponentsExample() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <section>
        <Heading level={3}>Tabs</Heading>
        <div style={{ marginTop: '1rem' }}>
          <Tabs defaultValue="tab1">
            <TabsList>
              <Tab value="tab1">Tab 1</Tab>
              <Tab value="tab2">Tab 2</Tab>
              <Tab value="tab3">Tab 3</Tab>
            </TabsList>
            <div style={{ marginTop: '1rem' }}>
              <TabsPanel value="tab1">Content for Tab 1</TabsPanel>
              <TabsPanel value="tab2">Content for Tab 2</TabsPanel>
              <TabsPanel value="tab3">Content for Tab 3</TabsPanel>
            </div>
          </Tabs>
        </div>
      </section>

      <section>
        <Heading level={3}>Accordion</Heading>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', marginTop: '1rem' }}>
          <Accordion title="Is it accessible?">
            Yes. It adheres to the WAI-ARIA design pattern.
          </Accordion>
          <Accordion title="Is it styled?">
            Yes. It comes with default styles that matches the other components' aesthetic.
          </Accordion>
        </div>
      </section>

      <section>
        <Heading level={3}>Modal</Heading>
        <div style={{ marginTop: '1rem' }}>
          <Button onClick={() => setIsModalOpen(true)}>Open Modal</Button>
          <Modal open={isModalOpen} onOpenChange={setIsModalOpen}>
            <ModalOverlay />
            <ModalContent>
              <ModalHeader>
                <ModalTitle>Modal Title</ModalTitle>
              </ModalHeader>
              <ModalBody>
                <Text>This is the modal body content. You can put any component here.</Text>
              </ModalBody>
              <ModalFooter>
                <Button variant="outline" onClick={() => setIsModalOpen(false)}>Cancel</Button>
                <Button variant="solid" color="primary" onClick={() => setIsModalOpen(false)}>Confirm</Button>
              </ModalFooter>
            </ModalContent>
          </Modal>
        </div>
      </section>

      <section>
        <Heading level={3}>Carousel</Heading>
        <div style={{ maxWidth: '400px', marginTop: '1rem' }}>
          <Carousel images={[
            { src: 'https://picsum.photos/400/200?random=1', alt: 'Slide 1' },
            { src: 'https://picsum.photos/400/200?random=2', alt: 'Slide 2' },
            { src: 'https://picsum.photos/400/200?random=3', alt: 'Slide 3' }
          ]} />
        </div>
      </section>

      <section>
        <Heading level={3}>Marketing / Display</Heading>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem', marginTop: '1rem' }}>
          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>Hero</Heading>
            <Hero
              title="Build faster with Erebus"
              subtitle="The ultimate design system for your next big project."
              primaryAction={{ label: 'Get Started', onClick: () => {} }}
              secondaryAction={{ label: 'Documentation', onClick: () => {} }}
            />
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>LogoCloud</Heading>
            <LogoCloud
              title="Trusted by innovative teams worldwide"
              logos={[
                { src: 'https://placehold.co/120x40?text=Logo+1', alt: 'Company 1' },
                { src: 'https://placehold.co/120x40?text=Logo+2', alt: 'Company 2' },
                { src: 'https://placehold.co/120x40?text=Logo+3', alt: 'Company 3' },
                { src: 'https://placehold.co/120x40?text=Logo+4', alt: 'Company 4' }
              ]}
            />
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>FeatureGrid</Heading>
            <FeatureGrid
              features={[
                { title: 'Feature 1', description: 'Description for feature 1' },
                { title: 'Feature 2', description: 'Description for feature 2' },
                { title: 'Feature 3', description: 'Description for feature 3' }
              ]}
            />
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>Testimonial</Heading>
            <Testimonial
              quote="This design system is amazing! It makes building applications so much faster."
              author="John Doe"
              role="Frontend Developer"
              avatarUrl="https://i.pravatar.cc/150?u=4"
            />
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>FAQ</Heading>
            <FAQ
              items={[
                { question: 'What is Erebus?', answer: 'Erebus is a comprehensive design system.' },
                { question: 'Is it free?', answer: 'Yes, it is open-source and free to use.' }
              ]}
            />
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>CTA</Heading>
            <CTA
              title="Ready to dive in?"
              description="Start building your application today with Erebus."
              primaryAction={{ label: 'Get Started', onClick: () => {} }}
              secondaryAction={{ label: 'Learn More', onClick: () => {} }}
            />
          </div>
        </div>
      </section>

      <section>
        <Heading level={3}>Data Display & States</Heading>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem', marginTop: '1rem' }}>
          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>Stat</Heading>
            <div style={{ display: 'flex', gap: '2rem' }}>
              <Stat label="Total Users" value="10,234" helpText="+12% from last month" />
              <Stat label="Revenue" value="$43,000" helpText="+5% from last month" />
            </div>
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>Timeline</Heading>
            <Timeline
              items={[
                { title: 'Project Started', description: 'Initial commit and setup.', date: 'Jan 1, 2026' },
                { title: 'Alpha Release', description: 'First version released for internal testing.', date: 'Mar 15, 2026' },
                { title: 'Public Beta', description: 'Opened to the public.', date: 'Jun 1, 2026' }
              ]}
            />
          </div>

          <div>
            <Heading level={4} style={{ marginBottom: '0.5rem' }}>EmptyState</Heading>
            <EmptyState
              title="No projects found"
              description="Get started by creating a new project."
              action={{ label: 'Create Project', onClick: () => {} }}
            />
          </div>
        </div>
      </section>
    </div>
  );
}
