// packages/react/src/avatar/Avatar.tsx
import { forwardRef, HTMLAttributes } from 'react';
import { cn } from '../utils';

export interface AvatarProps extends HTMLAttributes<HTMLDivElement> {
  src?: string;
  name?: string;
  size?: 'sm' | 'md' | 'lg';
}

export const Avatar = forwardRef<HTMLDivElement, AvatarProps>(
  ({ className, src, name, size = 'md', ...props }, ref) => {
    return (
      <div
        ref={ref}
        className={cn('erb-avatar', className)}
        data-size={size}
        role="img"
        aria-label={name}
        {...props}
      >
        {src ? (
          <img src={src} alt={name} className="erb-avatar__image" />
        ) : (
          <span className="erb-avatar__initials">{name ? name.charAt(0).toUpperCase() : '?'}</span>
        )}
      </div>
    );
  }
);
Avatar.displayName = 'Avatar';

// packages/angular/src/avatar/avatar.component.ts
import { Component, input } from '@angular/core';

export type AvatarSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'erb-avatar',
  standalone: true,
  template: `
    @if (src()) {
      <img [src]="src()" [alt]="name()" class="erb-avatar__image" />
    } @else {
      <span class="erb-avatar__initials">{{ initials }}</span>
    }
  `,
  host: {
    class: 'erb-avatar',
    '[attr.data-size]': 'size()',
    '[attr.role]': '"img"',
    '[attr.aria-label]': 'name()'
  }
})
export class AvatarComponent {
  src = input<string | undefined>();
  name = input<string>('');
  size = input<AvatarSize>('md');

  get initials(): string {
    const n = this.name();
    return n ? n.charAt(0).toUpperCase() : '?';
  }
}
