// packages/angular/src/FAQ/FAQ.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface FAQItemProps {
  question: string;
  answer: string;
}

@Component({
  selector: 'erb-faq',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="erb-faq" [ngClass]="className()">
      <div *ngFor="let item of items()" class="erb-faq-item">
        <p class="erb-faq-question">{{ item.question }}</p>
        <p class="erb-faq-answer">{{ item.answer }}</p>
      </div>
    </div>
  `,
})
export class FAQComponent {
  className = input<string>('');
  items = input.required<FAQItemProps[]>();
}

// packages/react/src/FAQ/FAQ.tsx
import React from 'react';

export interface FAQItemProps {
  question: string;
  answer: string;
}

export interface FAQProps {
  className?: string;
  items: FAQItemProps[];
}

export const FAQ: React.FC<FAQProps> = ({
  className = '',
  items,
  ...props
}) => {
  return (
    <div className={`erb-faq ${className}`} {...props}>
      {items.map((item, idx) => (
        <div key={idx} className="erb-faq-item">
          <p className="erb-faq-question">{item.question}</p>
          <p className="erb-faq-answer">{item.answer}</p>
        </div>
      ))}
    </div>
  );
};
